- name: create namespace
  openshift_v1_project:
    name: '{{ namespace }}'
  when: state == 'present'

- name: set service state to {{ state }}
  k8s_v1_service:
    name: postgresql
    namespace: '{{ namespace }}'
    labels:
      app: rhscl-postgresql-apb
      service: postgresql
    selector:
      app: rhscl-postgresql-apb
      service: postgresql
    ports:
    - name: port-5432
      port: 5432
      protocol: TCP
      target_port: 5432
    state: "{{ state }}"
  register: postgres_service

- name: scale deployment down
  openshift_v1_deployment_config:
    name: postgresql
    namespace: '{{ namespace }}'
    replicas: 0
    state: present
    selector:
      app: rhscl-postgresql-apb
      service: postgresql
  when: state == 'absent'

- include: dev.yml
  when: _apb_plan_id == "dev"

- include: prod.yml
  when: _apb_plan_id == "prod"

- name: delete replication controller
  k8s_v1_replication_controller:
    name: postgresql-1
    namespace: '{{ namespace }}'
    state: absent
  when: state == 'absent'

- name: Wait for postgres to come up
  wait_for:
    port: 5432
    host: "{{ postgres_service.service.spec.cluster_ip }}"
    timeout: 300
  when: state == 'present'

- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: postgres
      DB_HOST: postgresql
      DB_PORT: "5432"
      DB_USER: "{{ postgresql_user }}"
      DB_PASSWORD: "{{ postgresql_password }}"
      DB_NAME: "{{ postgresql_database }}"
  when: state == 'present'
