---
- name: Deploy rhscl-postgresql-apb to "{{ cluster }}"
  hosts: localhost
  gather_facts: True
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: unbind-rhscl-postgresql-apb
